package main

import (
	"albumGinSwagger/controllers"
	_ "albumGinSwagger/docs" // docs file is generated by Swag CLI, you have to import it.
	"github.com/gin-contrib/cors"
	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

// @title Album Store API
// @version 0.1
// @description Managing tool for album records

// @contact.name API Support
// @contact.email arian.khanjani@gmail.com

// @BasePath /
func main() {
	//log.Println("Server starting...")
	//log.Println("Connecting to database...")
	//config.Connect()
	gin.ForceConsoleColor()
	//log.Println("APIs initializing...")
	initServer()
}

func initServer() {
	r := gin.Default()
	r.Use(cors.Default())

	v1 := r.Group("/v1")
	{
		albums := v1.Group("/albums")
		id := albums.Group("/:id")

		albums.GET("", controllers.GetAlbums)
		albums.POST("", controllers.PostAlbums)
		id.GET("", controllers.GetAlbumById)
		//id.PATCH("", controllers.PatchAlbum)
		//id.DELETE("", controllers.DeleteAlbum)
	}

	// Swagger
	/*url := ginSwagger.URL("/swagger/doc.json") // The url pointing to API definition
	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler, url))*/

	v1.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))


	err := r.Run(":4080")
	if err != nil {
		return
	}
}