basePath: /
definitions:
  models.Album:
    properties:
      artist:
        type: string
      id:
        type: string
      price:
        type: number
      title:
        type: string
    type: object
info:
  contact:
    email: arian.khanjani@gmail.com
    name: API Support
  description: Managing tool for album records
  title: Album Store API
  version: "0.1"
paths:
  /v1/albums:
    get:
      consumes:
      - application/json
      description: Get details of all albums
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Album'
            type: array
      summary: Get all albums
    post:
      consumes:
      - application/json
      description: Create a new album with the input payload
      parameters:
      - description: Create Album
        in: body
        name: models.Album
        required: true
        schema:
          $ref: '#/definitions/models.Album'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Album'
      summary: Create a new album record
  /v1/albums/{id}:
    get:
      description: Get details of an album
      parameters:
      - description: Album ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Album'
            type: array
      summary: Get details of an album
swagger: "2.0"
